---
name: Molecule
on: push
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}

      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - run: pip3 install pytest-molecule pytest-testinfra

      - name: Run Molecule test
        uses: robertdebock/molecule-action@4.0.8
